print("Welcome to the Band Name Generator")
city = input("Whats`s the name of the city you grew up in?")
pet=input("What`s your pet`s name?")
print("Your band name could be " + city +" "+ pet + "!")
# #print("Welcome to the Band Name Generator")
# print("Your band name could be " + input("Whats`s the name of the city you grew up in?") +" "+ input("What`s your pet`s name?") + "!")